platform:
    - x86
    - x64

build_script:
- cmd: cd hello_world_application
- cmd: cmake -H. -B_build
- cmd: cmake --build _build
- cmd: cmake --build _build --target hello_world
- cmd: _build\Debug\hello_world.exe
- cmd: cd ..
- cmd: cd solver_application
- cmd: cmake -H. -B_build
- cmd: cmake --build _build
- cmd: cmake --build _build --target solver --config Release
- cmd: echo "Solver is done"
- cmd: cd _build
- cmd: cpack -G WIX

deploy:
    description: 'MSI release'
    provider: GitHub
    auth_token:
        secure: pp9qdC6EytDKxk6pAPdSgh8Y1wLLQqQlOYR+/EsyakD2CrhAehyPnA/24HnVr39t
    artifact: solver_application\_build\*.msi
    draft: false
    on:
        branch: master
        APPVEYOR_REPO_TAG: true
